# Generated by Django 5.0.6 on 2024-05-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strings', models.CharField(max_length=15)),
                ('fingering', models.CharField(max_length=15)),
                ('chordName', models.CharField(max_length=15)),
                ('enharmonicChordName', models.CharField(max_length=15)),
                ('voicingID', models.CharField(max_length=30)),
                ('tones', models.CharField(max_length=20)),
            ],
        ),
    ]
