# Generated by Django 5.0.6 on 2024-06-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chord',
            name='chordName',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='enharmonicChordName',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='fingering',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='strings',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='tones',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='voicingID',
        ),
        migrations.AddField(
            model_name='chord',
            name='chord_type',
            field=models.CharField(default='c', max_length=5),
        ),
        migrations.AddField(
            model_name='chord',
            name='imageUrl',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='chord',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='chord',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
